export const MEAL_PLANNER = 'MEAL_PLEANNER';
export const MEAL_PLANNER_EVENT_ADDED = 'MEAL_PLANNER/EVENT_ADDED';
export const MEAL_PLANNER_EVENT_EDITED = 'MEAL_PLANNER/EVENT_EDITED';
export const MEAL_PLANNER_EVENT_DELETE = 'MEAL_PLANNER/EVENT_DELETE';
